### PR TITLE
Bump jsonpath library to fix issue regarding filtering on nested array

### PR DESCRIPTION
**Pull request by tiopramayudi**
**What this PR does / why we need it**:

We found issue with library jsonpath that we used. It can't filter nested array correctly. Hence this PR will use latest release of jsonpath lib that address this issue

**Which issue(s) this PR fixes**:

Fixes #

**Does this PR introduce a user-facing change?**:

```release-note

```

**Checklist**

- [x] Added unit test, integration, and/or e2e tests
- [ ] Tested locally
- [ ] Updated documentation
- [ ] Update Swagger spec if the PR introduce API changes
- [ ] Regenerated Golang and Python client if the PR introduce API changes

### CODE REVIEW

**Comment by pradithya** [comment]
Can you add test correspond to the fix?

**Comment by tiopramayudi** [comment]
> Can you add test correspond to the fix?

added

**Comment by pradithya** [comment]
LGTM. Ideally you should create PR against `main` branch and then cherry pick it to `v0.20-branch`. Can  you also rename the branch to `v0.20-release`?

**Review by pradithya — APPROVED** [review]

**Comment by tiopramayudi** [comment]
> LGTM. Ideally you should create PR against `main` branch and then cherry pick it to `v0.20-branch`. Can you also rename the branch to `v0.20-release`?

done, I'll merge after all ci steps pass

**Pull request merged**
