### PR TITLE
Transformer: Update Content-Length header

### PR DESCRIPTION
**Pull request by ariefrahmansyah**
**What this PR does / why we need it**:

On writing HTTP response header, we are reusing (copying) the request's Content-Length header that might be different with actual response. This could raise EOF response (e.g.: `curl: (18) transfer closed with XX bytes remaining to`) from the standard transformer when there's preprocess / postprocess output modification due to a mismatch on Content-Length header. This PR sets the Content-Length to the correct request or response body size.

**Checklist**

- [x] Added tests
- [x] Tested locally

### CODE REVIEW

**Comment by tiopramayudi** [comment]
is it possible to create test for this kind of case?

**Comment by ariefrahmansyah** [comment]
> is it possible to create test for this kind of case?

I've updated the tests that check Content-Length header.

**Review by pradithya — APPROVED** [review]
LGTM

**Comment by pradithya** [comment]
I think the PR description requires update

**Pull request merged**
