### PR TITLE
Update UI so it can show version labels and filter version by labels

### PR DESCRIPTION
**Pull request by davidheryanto**
**What this PR does / why we need it**:

Update **list model versions** page and **view model version details** page so that the labels are shown and can be used as filters.

- List model versions page
  - Add labels column (show 2 labels by default, limit the no characters shown where user can hover to see the full labels)
  - Ability to filter model versions by labels
    - Click on any label will filter all versions by that label key, value
    - For advanced use case e.g. searching by multiple label key values and search terms, users can type the query directly in the search bar. For example `environment_name:myenv labels:foo IN (foo1, foo2), bar IN (bar3)` in order to filter model versions with environment `myenv` AND version labels (`foo:foo1` OR `foo:foo2`) AND `bar:bar3`

- View model version page
  - Add new labels row, listing all the labels

**Which issue(s) this PR fixes**:

N/A

**Does this PR introduce a user-facing change?**:

Example usage:
https://user-images.githubusercontent.com/5300554/109794053-6c3b8500-7c50-11eb-9ad7-e363e4610657.mp4

**Checklist**

- [ ] (N/A) Added unit test, integration, and/or e2e tests 
- [x] Tested locally
- [ ] (N/A) Updated documentation 
- [ ] (N/A) Update Swagger spec if the PR introduce API changes 
- [ ] (N/A) Regenerated Golang and Python client if the PR introduce API changes

### CODE REVIEW

**Comment by ariefrahmansyah** [comment]
Please remove `ui/package-lock.json` since Merlin is using yarn for package management.

**Review by ariefrahmansyah — CHANGES_REQUESTED** [review]
Please remove `ui/package-lock.json` since Merlin is using yarn for package management.

**Comment by davidheryanto** [comment]
> Please remove `ui/package-lock.json` since Merlin is using yarn for package management.

Removed

**Review by ariefrahmansyah — APPROVED** [review]
LGTM

**Pull request merged**
